import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === 'production';
const outdir = 'dist';

await copyPluginAssets();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

async function copyPluginAssets() {
	await mkdir(outdir, { recursive: true });
	await Promise.all([
		rm(`${outdir}/drawio`, { recursive: true, force: true }),
		rm(`${outdir}/tldraw-assets`, { recursive: true, force: true }),
	]);
	await Promise.all([
		copyFile('manifest.json', `${outdir}/manifest.json`),
	]);

	const [pluginStyles, tldrawStyles] = await Promise.all([
		readFile('styles.css', 'utf8'),
		readFile('node_modules/tldraw/tldraw.css', 'utf8'),
	]);
	await writeFile(`${outdir}/styles.css`, `${pluginStyles}\n\n${tldrawStyles}`);
}
